name: Sonar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Test
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet test Mastercard.Developer.OAuth1Signer.Tests/NetCore2/Mastercard.Developer.OAuth1Signer.Tests.NetCore2.csproj -c Release -l:"trx;LogFileName=tests.trx" -r:"bin/" /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput="bin/coverage.xml"
        dotnet publish $NETCORE2_TEST_PROJECT -c Release
        
    - name: SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        TEST_RESULTS_PATH: ./Mastercard.Developer.OAuth1Signer.Tests/NetCore2/bin
      with:
        args: >
          -Dsonar.organization=mastercard
          -Dsonar.projectName=oauth1-signer-csharp
          -Dsonar.projectKey=Mastercard_oauth1-signer-csharp
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=$SONAR_TOKEN
          -Dsonar.cs.vstest.reportsPaths=$TEST_RESULTS_PATH/tests.trx
          -Dsonar.cs.opencover.reportsPaths=$TEST_RESULTS_PATH/coverage.xml
