name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      NETCORE2_TEST_PROJECT: Mastercard.Developer.OAuth1Signer.Tests/NetCore2/Mastercard.Developer.OAuth1Signer.Tests.NetCore2.csproj
      NETCORE3_TEST_PROJECT: Mastercard.Developer.OAuth1Signer.Tests/NetCore3/Mastercard.Developer.OAuth1Signer.Tests.NetCore3.csproj

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        dotnet: [2.1.700, 2.1, 2.2, 3.0, 3.1]
        include:
          - dotnet: 2.1.700
            mono: none
            TEST_PROJECT: $NETCORE2_TEST_PROJECT
          - dotnet: 2.1
            mono: none
            TEST_PROJECT: $NETCORE2_TEST_PROJECT
          - dotnet: 2.2
            mono: none
            TEST_PROJECT: $NETCORE2_TEST_PROJECT
          - dotnet: 3.0
            mono: none
            TEST_PROJECT: $NETCORE3_TEST_PROJECT
          - dotnet: 3.1
            mono: none
            TEST_PROJECT: $NETCORE3_TEST_PROJECT
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Test
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet test $TEST_PROJECT -c Release -l:"trx;LogFileName=tests.trx" -r:"bin/" p:CollectCoverage=true p:CoverletOutputFormat="opencover" p:CoverletOutput="bin/coverage.xml"
